# OPER 685 
# Lesson 2 - Matrix Algebra and Stats review using Python

##  0. Import Libraries

In [1]:
import pandas as pd
import numpy as np
import random
import math
import matplotlib.pyplot as plt
from numpy.linalg import eig
%matplotlib inline

## 1.0 Vectors

### 1.1 Creating Vectors

In [2]:
v1 = np.array([2,3])
v2 = np.array([4,5])

In [3]:
type(v1)

numpy.ndarray

### 1.2 Vector Multiplication

In [4]:
np.dot(v1,v2)

23

### Mismatched vectors
Cannot use scalar product (i.e., dot product)

In [5]:
v2

array([4, 5])

In [6]:
v3 = np.array([2,3,4]) 
v3

array([2, 3, 4])

In [7]:
np.dot(v3, v2)

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)

### 1.3 Weighted sums of vectors

In [8]:
w1 = .25
w2 = .75
w1*v1+w2*v2

array([3.5, 4.5])

### 1.4 Vector norms
Note that instead of the L2 norm (standard euclidean norm) you can change the 2 to any number to calculate any arbitray p-norm.  Traditional choices are the L1 Norm (taxicab norm), and the L_infinity norm. 

In [9]:
v3 = np.array([1,2,3])
np.linalg.norm(v3, 2)

3.7416573867739413

$L_1$ norm is defined as sum of absolute values of components <br>
$\displaystyle \|{\boldsymbol {x}}\|_{1}:=\sum _{i=1}^{n}\left|x_{i}\right|$

In [10]:
np.linalg.norm(v3, 1)

6.0

$L_\infty$ norm is the maximum component <br> 
${\displaystyle \|\mathbf {x} \|_{\infty }:=\max _{i}\left|x_{i}\right|}$

In [11]:
np.linalg.norm(v3, np.inf)

3.0

## 2.0 Matrices

### 2.1 Creating an Matrix
This can be done two ways: </p>

**First:**  Create a list and then reshape the list into the matrix shape you want

In [12]:
a = (7.92, 5.68, 5.68, 6.29)

In [13]:
a = np.reshape(a, (2,2), order='C')
print(a)
print(a.shape)

[[7.92 5.68]
 [5.68 6.29]]
(2, 2)


In [15]:
b = np.reshape(a, (2,2), order='F')
print(b)
print(b.shape)

[[7.92 5.68]
 [5.68 6.29]]
(2, 2)


**Second:**  Directly create the matrix

In [16]:
c = np.array([[1, 0],[0, 1]])
print("Matrix C has shape" , c.shape)
print(c)

Matrix C has shape (2, 2)
[[1 0]
 [0 1]]


### 2.2 Matrix Transpose

In [17]:
m1 = np.array([[1,2],[3,4]])
m1

array([[1, 2],
       [3, 4]])

In [18]:
m1.T

array([[1, 3],
       [2, 4]])

### 2.3 *ij* 'th element of a Matrix

In [19]:
# i=0 and j=0 (recall Python 0 index)
m1[0,0]

1

In [20]:
m1[0,1]

2

In [21]:
#row slice, a vector
m1[1,:]

array([3, 4])

In [22]:
# Column slice, a vector
m1[:,1]

array([2, 4])

### 2.4 Matrix Addition

In [23]:
m1

array([[1, 2],
       [3, 4]])

In [24]:
m2 = np.array([[5,6],[7,8]])
m2

array([[5, 6],
       [7, 8]])

In [25]:
m1 + m2

array([[ 6,  8],
       [10, 12]])

### 2.5 Scalar Matrix multiplication

In [26]:
5*m1

array([[ 5, 10],
       [15, 20]])

### 2.6 Matrix Multiplication 
Numpy has many ways of doing matrix multiplcation and they are not all the same.  Stick with np.dot(a, b).

In [27]:
m1

array([[1, 2],
       [3, 4]])

In [28]:
m2 = np.array([[5,6],[1,2]])
print(m2)

[[5 6]
 [1 2]]


In [29]:
# Good
print(np.dot(m1,m2))

[[ 7 10]
 [19 26]]


In [27]:
#BAD - For easy problems these looks the same but as you get deeper into data science (tensors) they diverge.
print(np.matmul(m1,m2))

[[ 7 10]
 [19 26]]


In [30]:
#Also BAD - Just A shortcut for  matmul
#You can use @/matmul, and sometimes need to.  But be aware that @ != np.dot
print(m1@m2)

[[ 7 10]
 [19 26]]


#### Example
For simple matrices these two methods match but for tensors they do not.  Probably doesn't matter now but worth remembering. 

In [31]:
a = np.random.rand(2,3,3)
print(a)

[[[0.81293755 0.73844101 0.1962041 ]
  [0.62138537 0.787837   0.7860234 ]
  [0.58814563 0.43994756 0.13727539]]

 [[0.35378897 0.1185117  0.37942823]
  [0.77491973 0.88125417 0.08467242]
  [0.95483009 0.08682723 0.74248864]]]


In [32]:
b = np.random.rand(2,3,3)
print(b)

[[[0.91444259 0.17242092 0.04209062]
  [0.60725205 0.8455373  0.49957035]
  [0.70897651 0.13709292 0.44224454]]

 [[0.45440733 0.01402636 0.08078521]
  [0.66240899 0.62842298 0.91482974]
  [0.12631504 0.9203748  0.4279532 ]]]


In [33]:
c = (a@b)
print(c)

[[[1.33090863 0.79144504 0.48989047]
  [1.60390901 0.88104364 0.76734906]
  [0.90230949 0.49222016 0.30524946]]

 [[0.28719501 0.42865403 0.29937647]
  [0.94657529 0.64260003 0.90503541]
  [0.58518441 0.75132484 0.47431867]]]


In [34]:
d = np.dot(a,b)
print(d)

[[[[1.33090863 0.79144504 0.48989047]
   [0.88333827 0.65603715 0.82518729]]

  [[1.60390901 0.88104364 0.76734906]
   [0.90351896 1.22724677 1.10731669]]

  [[0.90230949 0.49222016 0.30524946]
   [0.57602285 0.4110675  0.50873802]]]


 [[[0.66449188 0.21322361 0.2418962 ]
   [0.28719501 0.42865403 0.29937647]]

  [[1.30379377 0.89035363 0.51031123]
   [0.94657529 0.64260003 0.90503541]]

  [[1.45227031 0.33983828 0.41192725]
   [0.58518441 0.75132484 0.47431867]]]]


### 2.7 Hadamard Product
Also called element wise matrix multiplication </p>
Be careful here.  If you were to use the np.matrix command to create matrices instead of arrays everything till now would look the same but you would not get the Hadamard product.  **Best practice is to use arrays in Python not matrices.** 

In [35]:
m1

array([[1, 2],
       [3, 4]])

In [36]:
m2

array([[5, 6],
       [1, 2]])

In [37]:
m1 * m2

array([[ 5, 12],
       [ 3,  8]])

In [38]:
m1=np.matrix([[1,2],[3,4]])
m2=np.matrix([[5,6],[1,2]])

In [39]:
m1*m2

matrix([[ 7, 10],
        [19, 26]])

### 2.8 Trace

In [40]:
m1

matrix([[1, 2],
        [3, 4]])

In [41]:
np.trace(m1)

5

### 2.9 Determinants

In [42]:
m1 = np.array([[1,2],[3,7]])
m1

array([[1, 2],
       [3, 7]])

In [43]:
np.linalg.det(m1)

0.9999999999999991

### 2.10 Matrix Inverse
Numpy can easily find the inverse of a matrix

In [44]:
m1

array([[1, 2],
       [3, 7]])

In [45]:
m3 = np.linalg.inv(m1)
print(m3)

[[ 7. -2.]
 [-3.  1.]]


### 2.11 Eigenvalues and Eigenvectors

In [46]:
A = np.array([[2, 1, 4], 
              [1, 3, 5],
              [4, 5, 4]])
w,v=eig(A)
print('E-values of A:', '\r\n',w)
print('E-vectors of A:','\r\n', v[0],'\r\n', v[1], '\r\n',v[2])

E-values of A: 
 [10.20312646  1.41987857 -2.62300503]
E-vectors of A: 
 [-0.41798254 -0.7676085  -0.48586808] 
 [-0.55647306  0.63908551 -0.53094957] 
 [-0.71807265 -0.04844484  0.69428003]


Remember Eigenvalue decomposition from slide 31? <br>
$A = E \Lambda E^{-1}$ <br>
Let's check that.  First we define $\Lambda$ 

In [47]:
l=np.diag(w)
l

array([[10.20312646,  0.        ,  0.        ],
       [ 0.        ,  1.41987857,  0.        ],
       [ 0.        ,  0.        , -2.62300503]])

In [48]:
v@l@np.linalg.inv(v)

array([[2., 1., 4.],
       [1., 3., 5.],
       [4., 5., 4.]])

Yep.  Our decomposition recreated A!

In [49]:
np.trace(A)

9

recall that the sum of the eigenvalues(A) = trace(A)

In [50]:
w@np.ones(3)

9.0

## 3. Statistics
If you want to import excel (.xls) instead of a .csv use the command pd.read_excel. You may also need to `pip install openpyxl` </p> <br>
Additionally, you need to either have the data file in the same folder as the Python code or you need to use more complicated code to tell Python where to look.

### 3.1 Import Data Set

In [51]:
bodymeasure = pd.read_csv("bodymeasurements.csv", index_col=None)

In [52]:
bodymeasure.shape

(33, 11)

Note that the data is imported as a pandas dataframe **not** as an array or matrix.  

In [53]:
type(bodymeasure)

pandas.core.frame.DataFrame

In [56]:
bodymeasure.head()

ID  Height  SITHT  UARM  FORE  Hand  ULEG  LLEG  FOOT  BRACH   TIBIO
0   1   165.8   88.7  31.8  28.1  18.7  40.3  38.9   6.7  88.36   96.53
1   2   169.8   90.0  32.4  29.1  18.3  43.3  42.7   6.4  89.81   98.61
2   3   170.7   87.7  33.6  29.5  20.7  43.7  41.1   7.2  87.80   94.05
3   4   170.9   87.1  31.0  28.2  18.6  43.7  40.6   6.7  90.97   92.91
4   5   157.5   81.3  32.1  27.3  17.5  38.1  39.6   6.6  85.05  103.94

we can still slice the data but we need different commands

In [57]:
bodymeasure.loc[0:1]

ID  Height  SITHT  UARM  FORE  Hand  ULEG  LLEG  FOOT  BRACH  TIBIO
0   1   165.8   88.7  31.8  28.1  18.7  40.3  38.9   6.7  88.36  96.53
1   2   169.8   90.0  32.4  29.1  18.3  43.3  42.7   6.4  89.81  98.61

In [58]:
bodymeasure.loc[:,'Height']

0     165.8
1     169.8
2     170.7
3     170.9
4     157.5
5     165.9
6     158.7
7     166.0
8     158.7
9     161.5
10    167.3
11    167.4
12    159.2
13    170.0
14    166.3
15    169.0
16    156.2
17    159.6
18    155.0
19    161.1
20    170.3
21    167.8
22    163.1
23    165.8
24    175.4
25    159.8
26    166.0
27    161.2
28    160.4
29    164.3
30    165.5
31    167.2
32    167.2
Name: Height, dtype: float64

In [59]:
np.mean(bodymeasure)

ID         17.000000
Height    164.563636
SITHT      85.566667
UARM       41.760606
FORE       28.024242
Hand       18.575758
ULEG       42.315152
LLEG       40.603030
FOOT        6.027273
BRACH      86.710909
TIBIO      96.034242
dtype: float64

In [60]:
np.std(bodymeasure)

ID         9.521905
Height     4.817822
SITHT      2.595879
UARM      52.923844
FORE       1.297557
Hand       0.933235
ULEG       2.214432
LLEG       2.063020
FOOT       0.626811
BRACH      4.271511
TIBIO      3.722308
dtype: float64

In [61]:
cov = bodymeasure[['Height', 'FORE', 'Hand']].cov()
print(cov)

           Height      FORE      Hand
Height  23.936761  4.482784  2.683778
FORE     4.482784  1.736269  0.626544
Hand     2.683778  0.626544  0.898144


In [62]:
cor = bodymeasure[['Height', 'FORE', 'Hand']].corr()
print(cor)

          Height      FORE      Hand
Height  1.000000  0.695355  0.578817
FORE    0.695355  1.000000  0.501730
Hand    0.578817  0.501730  1.000000


Note that covariance and correlation are ...correlated. Correlation is simply covariance on standardized data.

In [63]:
Xstnd = (bodymeasure - bodymeasure.mean())/(bodymeasure.std())

In [64]:
cov = Xstnd[['Height', 'FORE', 'Hand']].cov()
print(cov)

          Height      FORE      Hand
Height  1.000000  0.695355  0.578817
FORE    0.695355  1.000000  0.501730
Hand    0.578817  0.501730  1.000000


## 4.0 On your own

#### 4.1 Import the file `Lesson_2.xlsx`

In [2]:
df = pd.read_excel("Lesson_2.xlsx", index_col=None)

#### 4.2 Display the top 5 rows of this file using the ".head()" command

In [4]:
df.head(5)

Feature 1  Feature 2  Feature 3  Feature 4
0          2         -1          5         -4
1          3          0          6         -3
2          7         10          9         -9
3          2          0          2          0
4          4          1          4         -5

#### 4.3 Standardize the file contents

In [5]:
dfstnd = (df - df.mean())/(df.std())

#### 4.4 Create a vector called `silly` which is equal to the 5th sample from the standardized file 

In [19]:
silly = dfstnd.loc[4,:]
print(silly)

Feature 1   -0.077771
Feature 2   -0.747500
Feature 3   -0.516984
Feature 4   -0.046565
Name: 4, dtype: float64


#### 4.5 Calculate the covariance of the standardized file

In [20]:
dfcov = dfstnd.cov()
print(dfcov)

           Feature 1  Feature 2  Feature 3  Feature 4
Feature 1   1.000000   0.827111   0.917904  -0.931120
Feature 2   0.827111   1.000000   0.720452  -0.781608
Feature 3   0.917904   0.720452   1.000000  -0.905730
Feature 4  -0.931120  -0.781608  -0.905730   1.000000


#### 4.6 Discuss what you can uncover regarding the relationships of the 4 features to one another using the above covariance matrix

Features 1,2, and 3 are strongly correlated with eachother, and strongly inversely correlated with 4.

#### 4.7 Find the trace of the covariance matrix

In [21]:
print(np.trace(dfcov))

3.9999999999999996


#### 4.8 Find and display the eigenvalue and eigenvectors of the covariance matrix

In [22]:
val,vec = eig(dfcov)
print(val,"\n\n",vec)

[3.54717606 0.30724917 0.05771808 0.08785669] 

 [[-5.19096091e-01 -8.97488069e-02 -8.49990537e-01  6.98650112e-04]
 [-4.67128677e-01  8.49814512e-01  1.95669053e-01  1.46012727e-01]
 [-5.00971257e-01 -4.66595930e-01  3.55737066e-01  6.36213154e-01]
 [ 5.11231697e-01  2.28141809e-01 -3.35679683e-01  7.57570207e-01]]
