# CSCE 623 Day 3 Warmup coding

This activity focuses on python for numerical computation (e.g. linear algebra) using the numpy package for math variable storage and operator actions.

Students will review the basics of 
* importing packages (numpy) 
* entring numerical variable structures (scalars, vectors, matrix)
* showing the shapes (sizes of the dimensions) of those structures


First, we import numpy as `np` and show the numpy version using the numpy attribute  `__version__`.  In python, class attributes can be accessed using the `.` notation:  `np.__version__`. Printing something to an output cell can be accomplished using `print( )`, and you can place commas `,` between items if you want to include text (inside quotes) and values.  

Showing the version of an import is a quick way to ensure the import was successful.  It will also come in handy when you need to look up peculiarities of this version in the documentation since python packages change frequently.

In [1]:
import numpy as np
print("np version is", np.__version__)



np version is 1.21.1


## Instantiating and manipulating variables

----------
## STUDENT CODING REQUIRED

create three variables in numpy using `numpy.array()`:  a_scalar, a_vector and a_matrix.   Each should contain the number "42"   

In [3]:
#--------STUDENT CODING SECTION

#remove the None and add your code to create a scalar containing the value 42
a_scalar = np.array(42)

#remove the None and add your code to create a vector containing only the single value 42
a_vector = np.array([42])

#remove the None and add your code to create a matrix (2D numpy array) containing only the single value 42
a_matrix = np.array([[42]])

#--------END OF STUDENT CODING SECTION


Assuming that the variables were correctly instantiated, for each variable, we can print the variable, and print the shape of the variable using `.shape`

In [4]:
print("a_scalar =", a_scalar)
print("a_scalar.shape is ", a_scalar.shape)

print("a_vector =", a_vector)
print("a_vector.shape is ", a_vector.shape)

print("a_matrix =", a_matrix)
print("a_matrix.shape is ", a_matrix.shape)

a_scalar = 42
a_scalar.shape is  ()
a_vector = [42]
a_vector.shape is  (1,)
a_matrix = [[42]]
a_matrix.shape is  (1, 1)


-----
## STUDENT CODING REQURIED

for each of those variables, take the transpose using the built in `numpy` shortcut `T` and then print the resulting shapes of the transpose.   Did you notice anything interesting about the transposes?

In [5]:
#--------STUDENT CODING SECTION
#add code below to print the shapes of the transposes of each of the structures (a_scalar, a_vector, a_matrix)

print(a_scalar.T.shape)
print(a_vector.T.shape)
print(a_matrix.T.shape)

#--------END OF STUDENT CODING SECTION

()
(1,)
(1, 1)


Each of the variables (scalar, vector, matrix) contain only a single integer (42).  Lets Check to see if they are equivalent:  We will check for equality usint 3 different methods to see the differences and display the results:

> with `==`

> with `np.array_equal`

> with `np.array_equiv`



In [6]:
print("Numpy == checks")

print("a_scalar compare element equivalence to a_vector: ", a_scalar==a_vector)
print("a_scalar compare element equivalence to a_matrix: ", a_scalar==a_matrix)
print("a_vector compare element equivalence to a_matrix: ", a_vector==a_matrix)


print("Numpy array_equal checks")
print("a_scalar is np.array_equal to a_vector: ", np.array_equal(a_scalar,a_vector))
print("a_scalar is np.array_equal to a_matrix: ", np.array_equal(a_scalar,a_matrix))
print("a_vector is np.array_equal to a_matrix: ", np.array_equal(a_vector,a_matrix))


print("Numpy array_equiv checks")
print("a_scalar is np.array_equiv to a_vector: ", np.array_equiv(a_scalar,a_vector))
print("a_scalar is np.array_equiv to a_matrix: ", np.array_equiv(a_scalar,a_matrix))
print("a_vector is np.array_equal to a_matrix: ", np.array_equiv(a_vector,a_matrix))



Numpy == checks
a_scalar compare element equivalence to a_vector:  [ True]
a_scalar compare element equivalence to a_matrix:  [[ True]]
a_vector compare element equivalence to a_matrix:  [[ True]]
Numpy array_equal checks
a_scalar is np.array_equal to a_vector:  False
a_scalar is np.array_equal to a_matrix:  False
a_vector is np.array_equal to a_matrix:  False
Numpy array_equiv checks
a_scalar is np.array_equiv to a_vector:  True
a_scalar is np.array_equiv to a_matrix:  True
a_vector is np.array_equal to a_matrix:  True


## STUDENT ANSWER REQUIRED

in the space below, write your observation of these results... were they all the same?  why or why not
hint:  see the following operator APIs for Numpy:
* equal (shortcut is "=="): https://numpy.org/doc/stable/reference/generated/numpy.equal.html
* array_equiv:  https://numpy.org/doc/stable/reference/generated/numpy.array_equiv.html
* array_equal:  https://numpy.org/doc/stable/reference/generated/numpy.array_equal.html

---
STUDENT RESPONSE AREA:
* enter your answer here by opening this markdown chunk and typing your answer)


SOLUTION OBSERVATION: 

- Equivalence using the overridden primitive comparision operation returns true in all cases, however the boolean is returned in the number of brackets of the higher dimension of the pair, this leads me to believe that the operation attempts comparison by first attempting to type cast one of the entry data types to be the same as the other. array_equal appears not to do this and thus returns false for all. array_equiv also returns true but without the array brackets arround the boolean, I suspect that this means that this does similar casting to the first, but has an operation to return only the boolean.

---




------
For the vector you created above, we can also find out whether the vector is `np` `array_equal` to its transpose...

In [7]:
print("a_vector is np.array_equal to a_vector.T: ", np.array_equal(a_vector,a_vector.T))


a_vector is np.array_equal to a_vector.T:  True


------
lets make an actual meaningful vector in two different ways and see what happens.   Make a one-dimensional vector using `np.array([1, 2])`  and a 2-dimensional "row vector" using `np.array([[1, 2]])`, then display the shape of each of these as well as the shapes of their transposes. Finally, check for array_equal and array_equiv

In [8]:
b_vector = np.array([1, 2])
print("b_vector: ", b_vector, ", shape = ", b_vector.shape)

b_rowvector = np.array([[1, 2]])
print("b_rowvector: ", b_rowvector, ", shape = ", b_rowvector.shape)

print("b_vector np.array_equal to b_rowvector: ", np.array_equal(b_vector,b_rowvector))
print("b_vector np.array_equiv to b_rowvector: ", np.array_equiv(b_vector,b_rowvector))

b_vector:  [1 2] , shape =  (2,)
b_rowvector:  [[1 2]] , shape =  (1, 2)
b_vector np.array_equal to b_rowvector:  False
b_vector np.array_equiv to b_rowvector:  True


----------
## STUDENT CODE REQUIRED

Given what you saw in the results, create two different COLUMN vectors containing the integer values 1 and 2 using  two different techniques (directly via array creation, and indirectly using Transpose of the previous rowvector).  

In [11]:
#--------STUDENT CODING SECTION

#replace None with a direct instantiation of a column vector with values 1 and 2
c_columnvector1 = np.array([[1],[2]])


#replace None with a transpose of the b_rowvector instantiated in the previous code chunk
c_columnvector2 = b_rowvector.T


#--------END OF STUDENT CODING SECTION

Now lets display their values and shapes, and check for equality and equivalence

In [12]:
print("c_columnvector1: ", c_columnvector1, "; shape = ", c_columnvector1.shape)
print("c_columnvector2: ", c_columnvector2, "; shape = ", c_columnvector2.shape)
print("c_columnvector1 np.array_equal to c_columnvector2: ", np.array_equal(c_columnvector1,c_columnvector2))
print("c_columnvector1 np.array_equiv to c_columnvector2: ", np.array_equiv(c_columnvector1,c_columnvector2))

c_columnvector1:  [[1]
 [2]] ; shape =  (2, 1)
c_columnvector2:  [[1]
 [2]] ; shape =  (2, 1)
c_columnvector1 np.array_equal to c_columnvector2:  True
c_columnvector1 np.array_equiv to c_columnvector2:  True


------
## Multiplication

There are different meanings of "mulitplication" in `numpy`.   One must distinguish element-wise multiplication from matrix multiplication.

## STUDENT CODING REQUIRED

Create two different matrices  `[[1,2],[3,4]]` in `m1` and `[[5,6],[7,8]]` in `m2` 

In [13]:
#--------STUDENT CODING SECTION

#replace "None" with the instantiation of m1:
m1 = np.array([[1,2],[3,4]])



#replace "None" with the instantiation of m2:
m2 = np.array([[5,6],[7,8]])


#--------END OF STUDENT CODING SECTION

Lets see what the differences are using `*`,`@`, `np.mult`, `np.dot` to operate on these two matrices.  Which ones are element-wise multiplication and which are matrix multiplication?

In [14]:
print("m1: \n",m1)
print("m2: \n",m2)
print("results of *:\n" , m1*m2)
print("results of @:\n" , m1@m2)
print("results of np.mult:\n" , np.multiply(m1,m2))
print("results of np.dot:\n" , np.dot(m1,m2))

m1: 
 [[1 2]
 [3 4]]
m2: 
 [[5 6]
 [7 8]]
results of *:
 [[ 5 12]
 [21 32]]
results of @:
 [[19 22]
 [43 50]]
results of np.mult:
 [[ 5 12]
 [21 32]]
results of np.dot:
 [[19 22]
 [43 50]]


## STUDENT OBSERVATION REQUIRED:

Given what you saw above, what do you think thes operators are doing?

Hint:  See the `numpy` API

---
STUDENT RESPONSE AREA:
(enter your answer here by opening this markdown chunk and typing your answer)

OBSERVATION:

Multiply and * are both the Hadamard product (element-wise product).

Dot and @ are the result of proper matrix multiplication.

---

Lets see what happens if we create a column vector `y` to be (the transpose of) `[[3, 4]]` and compute the dot product of `y.T` and `y`.   

Create the vector first and print out its shape to ensure you have a column vector of shape (2,1).  Challenge:  can you define the column vector y in a single line of code?

Then take the dot product of `y.T` and `y` and display the result.  What shape is the result?
What does the result appear to be?   



In [15]:
y = np.array([[3,4]]).T
print("y.shape: ",y.shape)
print("dot product of y.T and y:", np.dot(y.T,y))

y.shape:  (2, 1)
dot product of y.T and y: [[25]]


------

So far we have been working with structures containing integers.  Numpy also allows structures of floating point numbers, but if you want to represent an integer value as a float you need to put a decimal point after the intger, like this

>`numpy.array([[1., 2.]])`  

One important activity in science and engineering - and especially machine learning - is computing a summary value from a set of errors.  Some common summary representations include the "sum of squared errors" (RSS), the "mean squared error" (MSE) and the "Root Mean Squared Error" (RMSE)

Suppose you had a column vector of error values `errors` : `[[-1.],[1.],[2.],[-1.],[3.]]` like this:

In [16]:
errors = np.array([[-1.],[1.],[2.],[-1.],[3.]])
print("errors:\n", errors, "\nerrors.shape:\n", errors.shape)

errors:
 [[-1.]
 [ 1.]
 [ 2.]
 [-1.]
 [ 3.]] 
errors.shape:
 (5, 1)


and suppose you wanted to find the  Sum of Squared errors... you could use a loop to compute the square of each value, and sum them like this... 

In [17]:
rss_loop = 0
for err in errors:
  rss_loop += np.square(err)

print("computing RSS using loop, rss_loop:", rss_loop)

computing RSS using loop, rss_loop: [16.]


...but that is not very efficient for large vectors... if you were a little more crafty you might realize that loops run slow and you could skip the loop by use numpy to square each individual the elements at first and then use numpy to sum them.  

## STUDENT CODING REQUIRED:

Implement the loop technique and the vectorized technique to find the RSS using each method and display the results

hint:  use the `square` and `sum` operators in `numpy` to operate driectly on the `errors` vector

In [18]:
#--------STUDENT CODING SECTION

# replace "None" with your vectorized solution for computing the sum of squared errors
rss_vectorized = errors**2

#--------END OF STUDENT CODING SECTION

In [19]:
print("computing RSS using vectorized method, rss_loop:", rss_vectorized)


computing RSS using vectorized method, rss_loop: [[1.]
 [1.]
 [4.]
 [1.]
 [9.]]


## STUDENT CODING REQUIRED

If you are really crafty, you might recognize that we can do this entire RSS calculation using a single call to one of numpy's matrix operations (instead of a calls to `np.square` and `np.sum`).  Do that next and print out the result.

Hint:  Look for a `numpy` linear algebra function which performa the operation of multiplying a set of values together and suming the result.   Using such an operator on a vector and itself would yield the desired result - sum of squares - but remember that you will need to make the operation compatible for the linear algebra multiplication to be valid

In [20]:
#--------STUDENT CODING SECTION

# replace `None` with the desired code to compute the RSS
rss_dot = np.sum(errors**2)


#--------END OF STUDENT CODING SECTION

In [21]:
print("computing RSS using dot product, rss_dot:", rss_dot)

computing RSS using dot product, rss_dot: 16.0


Notice that this is printing the results inside a numpy matrix.   Lets see how we can get this as a scalar value instead of a numpy array containing that value. 
When the numpy array is a single value we can use the `.item()` attribute of the array to obtain that value.

In [ ]:
print("computing RSS using dot product, rss_dot:", rss_dot.item())

## STUDENT CODING REQUIRED

Challenge:  Can you compute the *root mean squared error* (aka RMSE) of this error vector using a single line of code?  print the results when done.

In [24]:
#--------STUDENT CODING SECTION

#replace the `None` with the code to compute rmse
rmse = np.sqrt(np.sum(errors**2)/len(errors))


print("Compute the mean of the squared errors by dividing by the vector length: RMSE = ", rmse)


#--------END OF STUDENT CODING SECTION

Compute the mean of the squared errors by dividing by the vector length: RMSE =  1.7888543819998317
