In [1]:
import numpy as np
import ProjectFunctions as PF



In [2]:
P, S = PF.create_one_step_P_matrix()
# NUM_ACFT = 12
# MAX_SORTIES = 8
# PROB_PASS_POSTFLT_INSP = 0.8
# PROB_REPAIR_FRONTSHOP = 0.7
# PROB_PASS_POST_BACKSHOP_INSP = 0.8


P matrix computed in 3.2717 secs.

Sum of |S| = 1820 rows is 1820.0.

Number of non-zero elements is 30856.


In [8]:
# Initial State:
print(PF.state_to_index(S,[0,3,3,3,3]))
print(PF.index_to_state(S,265))

STARTING_INDEX = 265

a = np.zeros(len(P))
a[STARTING_INDEX] = 1

print(np.nonzero(a), np.take(a, np.nonzero(a)))

265
[0 3 3 3 3]
(array([265]),) [[1.]]


In [10]:
t1 = a*P
print(np.nonzero(t1)[1], np.take(t1, np.nonzero(t1)[1]))

[ 265  629  674  915  960  996 1135 1180 1216 1244 1345 1381 1409 1501
 1529 1613] [[2.16000e-04 2.59200e-03 1.51200e-03 1.03680e-02 1.81440e-02 3.52800e-03
  1.38240e-02 7.25760e-02 4.23360e-02 2.74400e-03 9.67680e-02 1.69344e-01
  3.29280e-02 2.25792e-01 1.31712e-01 1.75616e-01]]


In [24]:
print(PF.index_to_state(S,1750))

[8 0 0 0 4]


In [ ]:
# Long term (pi) calculations

# Define the p-matrix
P
cardS, _ = np.shape(P)
I = np.matrix(np.eye(cardS))

# Construct system of linear equations, Ax=b
# LHS
A_bal = I-P.T
A_norm = np.matrix(np.ones(cardS))

# RHS
b_bal = np.matrix(np.zeros((cardS,1)))
b_norm = np.matrix(1)

# vertically stack
A = np.vstack((A_bal,A_norm))
b = np.vstack((b_bal,b_norm))

# Remove an overdetermining member equation
A = np.delete(A,0,0)
b = np.delete(b,0,0)

# Solve
pi = np.linalg.solve(A,b)
